"""Tests for host/bridge_doctor.py — the cross-layer stack diagnosis.

The doctor's whole value is naming the RIGHT layer, so these tests drive it
from canned command output: every scenario below cost a real debugging session
at least once, and each must produce its own distinct finding rather than the
generic "bridge is down".

Run: python3 tests/test_bridge_doctor.py   (or via pytest)
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "host"))
import bridge_doctor as bd
import platform_seam  # noqa: E402

UID = 501
HOST_IP = "192.168.3.154"

LSOF_LISTEN_OK = (
    "COMMAND   PID       USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME\n"
    "Python  10989 pitforster    4u  IPv4  0x5627      0t0  TCP "
    f"{HOST_IP}:9000 (LISTEN)\n"
    "Python  10989 pitforster    5u  IPv4  0x885d      0t0  TCP "
    "127.0.0.1:9001 (LISTEN)\n")

LSOF_ESTABLISHED = (
    "COMMAND   PID       USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME\n"
    "Python  10989 pitforster    6u  IPv4  0x3eb2      0t0  TCP "
    f"{HOST_IP}:9000->192.168.3.244:2048 (ESTABLISHED)\n")


def ifconfig(en0_addrs=(HOST_IP, "192.168.3.240"), en8_addrs=()):
    """Render an ifconfig dump with the given addresses per interface."""
    out = ["lo0: flags=8049<UP,LOOPBACK> mtu 16384",
           "\tinet 127.0.0.1 netmask 0xff000000"]
    for name, addrs in (("en0", en0_addrs), ("en8", en8_addrs)):
        out.append(f"{name}: flags=8863<UP,BROADCAST,RUNNING> mtu 1500")
        out.append("\tether 00:0c:6c:0b:0e:ad")
        for a in addrs:
            out.append(f"\tinet {a} netmask 0xffffff00 broadcast 192.168.3.255")
    return "\n".join(out) + "\n"


def make_run(*, launchd_loaded=True, launchd_disabled=False, listening=True,
             established=True, en0=(HOST_IP, "192.168.3.240"), en8=(),
             default_if="en0", basilisk=True, etherhelper=True,
             sheepshaver=False):
    """Build a fake `run` that answers each probe command from the flags above."""
    def run(argv, timeout=4.0):
        cmd = " ".join(argv)
        if cmd == "launchctl list":
            return (f"10989\t0\t{bd.LAUNCHD_LABEL}\n" if launchd_loaded
                    else "-\t0\tcom.apple.something\n")
        if cmd.startswith("launchctl print-disabled"):
            flag = "true" if launchd_disabled else "false"
            return f'\t"{bd.LAUNCHD_LABEL}" => {flag}\n'
        if "-sTCP:LISTEN" in cmd:
            return LSOF_LISTEN_OK if listening else ""
        if "-sTCP:ESTABLISHED" in cmd:
            return LSOF_ESTABLISHED if established else ""
        if cmd == "ifconfig":
            return ifconfig(en0, en8)
        if cmd.startswith("route"):
            return (f"   route to: default\n  interface: {default_if}\n"
                    if default_if else "")
        if cmd.startswith("pgrep"):
            pattern = argv[-1]
            if pattern == "BasiliskII":
                return "11000 /Applications/BasiliskII.app/…/BasiliskII\n" if basilisk else ""
            if pattern == "SheepShaver":
                return "12000 /Applications/SheepShaver\n" if sheepshaver else ""
            if pattern == "etherhelpertool":
                return "11002 /…/etherhelpertool en8\n" if etherhelper else ""
        return ""
    return run


LOCAL_ENV_OK = (
    "# generated by install_bridge.py\n"
    "# APPLEBRIDGE_HOST_IP is deliberately NOT set: slirp needs the 0.0.0.0 bind.\n"
    "APPLEBRIDGE_EMULATOR_APP=/Applications/BasiliskII.app\n")


def make_read(ether="etherhelper/en8", netmode="etherhelper/en8",
              local_env=LOCAL_ENV_OK, deploy_stamp="abc1234-20260728-090000"):
    def read(path):
        if path.endswith(".netmode"):
            return (netmode + "\n") if netmode else ""
        if path.endswith("local.env"):
            return local_env
        if path.endswith(".deploy_stamp"):
            return deploy_stamp
        return ("disk /Users/pit/System761.dmg\nscreen win/1024/768\n"
                + (f"ether {ether}\n" if ether else "")
                + "ramsize 130023424\n")
    return read


def report(**kw):
    read_kw = {k: kw.pop(k) for k in ("ether", "netmode") if k in kw}
    # Whether the launchd agent is INSTALLED is now a separate input from
    # whether it is loaded; default True so every pre-existing case keeps its
    # meaning, and the two cases that care state it.
    installed = kw.pop("agent_installed", True)
    host_ip = kw.pop("host_ip", HOST_IP)
    for k in ("local_env", "deploy_stamp"):
        if k in kw:
            read_kw[k] = kw.pop(k)
    # `exists` answers for three different questions now: the launchd plist,
    # the recorded emulator bundle, and the deployed server. Default them all to
    # present so every pre-existing case keeps its meaning; the cases that care
    # pass a callable.
    missing = kw.pop("missing_paths", ())
    def exists(path):
        if any(path.endswith(m) for m in missing):
            return False
        return installed if path.endswith(".plist") else True
    # These cases are ABOUT a macOS host (launchd, ~/Library, `route -n get
    # default`), so they say so rather than inheriting whatever platform the
    # suite runs on — the seam exists precisely so that is a value.
    return bd.collect(run=make_run(**kw), read=make_read(**read_kw), uid=UID,
                      host_ip=host_ip, exists=exists,
                      service=platform_seam.service(platform_name="darwin"))


def keys(rep):
    return {f["key"] for f in rep["findings"]}


# --- the healthy stack ------------------------------------------------------
def test_healthy_stack_is_ok():
    rep = report()
    assert rep["verdict"] == "ok", rep["findings"]
    assert rep["ok"] is True
    assert rep["findings"] == []


def test_healthy_stack_reports_observed_facts():
    p = report()["probes"]
    assert p["launchd"]["loaded"] is True and p["launchd"]["pid"] == 10989
    assert p["sockets"]["listen"]["daemon_port"] == HOST_IP
    assert p["sockets"]["listen"]["control_port"] == "127.0.0.1"
    assert p["sockets"]["guest_peer_ip"] == "192.168.3.244"
    assert p["network"]["host_ip_interfaces"] == ["en0"]
    assert p["network"]["default_route_interface"] == "en0"
    assert p["processes"]["etherhelpertool"]["pid"] == 11002
    assert p["emulator_prefs"]["ether"] == "etherhelper/en8"


# --- host server layer ------------------------------------------------------
def test_launchd_disabled_is_named_as_deliberate():
    rep = report(launchd_disabled=True, listening=False, established=False)
    assert "launchd_disabled" in keys(rep)
    assert rep["verdict"] == "error"
    fix = [f for f in rep["findings"] if f["key"] == "launchd_disabled"][0]["fix"]
    assert "launchctl enable" in fix and "bootstrap" in fix


def test_launchd_absent_reported_without_disabled_claim():
    """An INSTALLED agent that is not loaded: bootstrap advice is correct."""
    rep = report(launchd_loaded=False, listening=False, established=False)
    assert "launchd_absent" in keys(rep)
    assert "launchd_disabled" not in keys(rep)


def test_a_machine_without_the_agent_is_not_told_to_bootstrap_it():
    """R13: most installations have no plist and start the server by hand.

    Telling their owner to bootstrap one names a component they never had — a
    false lead in an authoritative tone, which is worse than silence.
    """
    rep = report(launchd_loaded=False, listening=False, established=False,
                 agent_installed=False)
    k = keys(rep)
    assert "launchd_absent" not in k, "must not advise bootstrapping an absent plist"
    assert "host_server_not_running" in k, "the real problem is that nothing listens"
    remedy = [f for f in rep["findings"] if f["key"] == "host_server_not_running"][0]
    assert "run_server.sh" in remedy["fix"]
    assert "/dev/null" in remedy["fix"], "the R12 trap must not be walked into here"


def test_a_hand_started_server_that_IS_listening_is_not_an_error():
    """No agent and no complaint: this is simply how that machine is run."""
    rep = report(launchd_loaded=False, agent_installed=False)
    assert "host_server_not_running" not in keys(rep)
    assert "launchd_absent" not in keys(rep)


def test_loaded_but_no_control_port_flags_crash_loop():
    rep = report(listening=False, established=False)
    assert "control_port_closed" in keys(rep)


# --- the .154 alias placement rule -----------------------------------------
def test_duplicate_alias_is_an_error_with_a_removal_command():
    rep = report(en8=(HOST_IP,))
    assert "host_ip_duplicate" in keys(rep)
    f = [x for x in rep["findings"] if x["key"] == "host_ip_duplicate"][0]
    assert f["level"] == "error"
    assert f"ifconfig en8 -alias {HOST_IP}" in f["fix"]     # strip the stray one
    assert "en0" not in f["fix"].split(";")[0]              # keep the good one


def test_alias_on_wrong_interface_is_flagged():
    rep = report(en0=("192.168.3.240",), en8=(HOST_IP,), default_if="en0")
    assert "host_ip_wrong_interface" in keys(rep)


def test_missing_alias_is_flagged():
    rep = report(en0=("192.168.3.240",))
    assert "host_ip_missing" in keys(rep)


# --- emulator transport backend --------------------------------------------
def test_slirp_warns_about_appletalk_even_though_tcp_works():
    rep = report(ether="slirp", netmode=None)
    f = [x for x in rep["findings"] if x["key"] == "ether_slirp"][0]
    assert "AppleTalk" in f["message"]          # the non-obvious consequence
    assert rep["verdict"] == "warn"
    assert rep["ok"] is True                    # TCP works: not a hard failure


def test_a_wildcard_bind_is_not_a_missing_alias():
    # Observed live 2026-07-27, on the deployed server: with no configured
    # address the doctor resolved 0.0.0.0, looked for an interface carrying that
    # literal, found none, and reported ERROR "the daemon dials that address" —
    # an address nothing dials. It is also the DEFAULT state of a slirp install,
    # where the installer deliberately writes none (R7), so the wrong reading
    # was about to become the common one.
    rep = report(host_ip=bd.BIND_ALL)
    assert "host_ip_missing" not in keys(rep)
    f = [x for x in rep["findings"] if x["key"] == "host_ip_wildcard"][0]
    assert f["level"] == "info"
    assert HOST_IP in f["message"], "must still name what the guest can dial"


def test_a_deliberately_installed_slirp_host_is_informed_not_warned():
    # D-018: the installer configures this branch on purpose, so warning about
    # it would tell an operator their correct installation is broken. The cost
    # is still stated, because TCP keeps working and the gap is otherwise
    # invisible — it shows up as an empty Chooser, not as a network error.
    rep = report(ether="slirp", netmode="slirp")
    f = [x for x in rep["findings"] if x["key"] == "ether_slirp_by_design"][0]
    assert f["level"] == "info" and "AppleTalk" in f["message"]
    assert "ether_slirp" not in keys(rep) and "ether_drift" not in keys(rep)


def test_the_slirp_warning_no_longer_names_one_machines_interface():
    # `set 'ether etherhelper/en8'` was advice as machine-specific as the
    # addresses R1 removed, and wrong on any host without that NIC.
    rep = report(ether="slirp", netmode=None)
    fix = [x for x in rep["findings"] if x["key"] == "ether_slirp"][0]["fix"]
    assert "en8" not in fix


def test_backend_drift_against_netmode_is_flagged():
    rep = report(ether="slirp", netmode="etherhelper/en8")
    assert {"ether_slirp", "ether_drift"} <= keys(rep)


def test_dead_etherhelper_is_an_error_only_when_that_backend_is_selected():
    rep = report(etherhelper=False, established=False)
    assert "etherhelper_dead" in keys(rep)
    # On slirp there IS no helper process, so its absence must not be reported.
    rep = report(etherhelper=False, established=False, ether="slirp",
                 netmode=None)
    assert "etherhelper_dead" not in keys(rep)


def test_no_helper_without_a_running_emulator_is_not_an_error():
    rep = report(basilisk=False, etherhelper=False, established=False)
    assert "etherhelper_dead" not in keys(rep)
    assert "emulator_down" in keys(rep)


# --- link state -------------------------------------------------------------
def test_emulator_up_but_no_guest_link_is_informational():
    rep = report(established=False)
    assert "no_guest_link" in keys(rep)
    assert rep["verdict"] == "info"
    assert rep["ok"] is True


def test_sheepshaver_counts_as_a_running_emulator():
    rep = report(basilisk=False, sheepshaver=True, etherhelper=False,
                 established=False)
    assert "emulator_down" not in keys(rep)


# --- short_reason: what the control port replies while the daemon is down ----
def test_short_reason_names_the_worst_finding_first():
    msg = bd.short_reason(report(launchd_disabled=True, en8=(HOST_IP,),
                                 listening=False, established=False))
    assert "DISABLED" in msg and "Fix:" in msg


def test_short_reason_prefers_errors_over_warnings():
    msg = bd.short_reason(report(ether="slirp", netmode=None, en8=(HOST_IP,)))
    assert "MORE THAN ONE interface" in msg        # the error, not the slirp warn


def test_short_reason_falls_back_to_the_retry_hint_when_all_is_well():
    msg = bd.short_reason(report(established=False))
    assert "30 s" in msg or "30s" in msg


def test_short_reason_reports_a_missing_emulator_plainly():
    rep = report(basilisk=False, etherhelper=False, established=False)
    assert "No emulator" in bd.short_reason(rep)


# --- robustness: probes must degrade, never raise ---------------------------
def test_every_probe_failing_still_yields_a_report():
    """Every input is injected, including whether the agent exists.

    Left to the real filesystem this passed on a machine that happens to have
    the plist and failed on one that does not — which is the very divergence
    bridge_doctor is for. A test that reads the developer's disk cannot detect
    that class of fault; it embodies it.
    """
    rep = bd.collect(run=lambda argv, timeout=4.0: "",
                     read=lambda path: "", uid=UID, host_ip=HOST_IP,
                     exists=lambda _p: True,          # agent installed, not loaded
                     service=platform_seam.service(platform_name="darwin"))
    assert rep["verdict"] == "error"          # missing job + missing alias
    assert {"launchd_absent", "host_ip_missing"} <= keys(rep)
    assert isinstance(bd.format_text(rep), str)


def test_every_probe_failing_on_a_machine_without_the_agent():
    """The same collapse on an installation that has no launchd job at all."""
    rep = bd.collect(run=lambda argv, timeout=4.0: "",
                     read=lambda path: "", uid=UID, host_ip=HOST_IP,
                     exists=lambda _p: False,
                     service=platform_seam.service(platform_name="darwin"))
    assert rep["verdict"] == "error"
    k = keys(rep)
    assert "host_server_not_running" in k
    assert "launchd_absent" not in k
    assert isinstance(bd.format_text(rep), str)


def test_run_helper_survives_a_missing_binary():
    assert bd._run(["definitely-not-a-real-binary-xyz"]) == ""


def test_format_text_lists_the_probe_lines_and_verdict():
    text = bd.format_text(report())
    for expected in ("launchd job:", ":9000 / :9001:", "default route:",
                     "emulator ether:", "guest peer IP:", "verdict: ok"):
        assert expected in text, text


# --- the peer probe must not depend on a configured host address ------------
# Observed 2026-07-28 on a freshly booted slirp guest: `lsof` showed the link
# ESTABLISHED and the bridge was answering commands, while the doctor said
# "Emulator is up but no guest is connected to :9000 yet". The peer pattern was
# anchored on the CONFIGURED host IP, and the slirp branch has none — the server
# binds 0.0.0.0 by design (D-018). So the probe silently matched nothing across
# the entire branch the installer configures, and reported that as a fact about
# the guest.
SLIRP_ESTABLISHED = (
    "COMMAND    PID       USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME\n"
    "Python    4590 pitforster    6u  IPv4  0x6554      0t0  TCP "
    "192.168.3.240:9000->192.168.3.240:49492 (ESTABLISHED)\n"
    "BasiliskI 4604 pitforster   14u  IPv4  0x6ec0      0t0  TCP "
    "192.168.3.240:49492->192.168.3.240:9000 (ESTABLISHED)\n")


def test_the_peer_is_seen_on_a_wildcard_bind_with_no_configured_address():
    p = bd.probe_sockets(lambda argv: SLIRP_ESTABLISHED)
    assert p["guest_peer_ip"] == "192.168.3.240", p


def test_the_peer_is_the_remote_end_not_the_local_one():
    # Both directions of the same connection appear in lsof output. Taking the
    # first address on the line would report the SERVER's address as the guest's.
    p = bd.probe_sockets(lambda argv: SLIRP_ESTABLISHED)
    assert p["guest_peer_ip"] != "0.0.0.0"
    p2 = bd.probe_sockets(lambda argv: LSOF_ESTABLISHED)
    assert p2["guest_peer_ip"] == "192.168.3.244", p2


def test_no_established_link_still_reports_no_peer():
    assert bd.probe_sockets(lambda argv: "")["guest_peer_ip"] is None


# --- the installer's contract: is this machine correctly INSTALLED? ---------
# Everything above diagnoses a RUNNING stack. These ask the other question, and
# nothing did before: `--dry-run` proves the plan, tests/test_installer.py
# proves every branch of the plan, and neither says a word about the state of
# the computer afterwards. A plan can be right and the result still wrong.

def test_a_correct_install_adds_no_findings():
    assert "local_env_has_host_ip" not in keys(report())
    assert "emulator_app_stale" not in keys(report())
    assert "deploy_missing" not in keys(report())


def test_a_host_address_in_local_env_is_an_error_on_slirp():
    # R1/R2, and the reason it is an ERROR rather than a warning: a specific
    # address BINDS SUCCESSFULLY and then waits forever for a connection that
    # arrives on a different one. Nothing about it looks broken.
    rep = report(ether="slirp", netmode="slirp",
                 local_env="APPLEBRIDGE_HOST_IP=192.168.3.154\n")
    assert "local_env_has_host_ip" in keys(rep)
    f = [x for x in rep["findings"] if x["key"] == "local_env_has_host_ip"][0]
    assert f["level"] == "error"
    assert "192.168.3.154" in f["message"]


def test_the_comment_explaining_the_absence_is_not_read_as_an_assignment():
    # The generated file says "APPLEBRIDGE_HOST_IP is deliberately NOT set" in a
    # comment. A substring check reads that as the address being configured —
    # the same near-miss that made `grep -c` look like a failed install on the
    # 2013 MacBook, 2026-07-28.
    assert "local_env_has_host_ip" not in keys(report(local_env=LOCAL_ENV_OK))


def test_a_commented_out_assignment_is_not_an_assignment_either():
    # What protects here is the EXACT KEY comparison, not the leading-# skip:
    # "#APPLEBRIDGE_HOST_IP" is simply not the key being looked for. Verified by
    # mutation — removing the # skip changes no outcome — so these cases pin the
    # property that does the work rather than the line that looks like it does.
    for text in ("#APPLEBRIDGE_HOST_IP=192.168.3.154\n",
                 "# APPLEBRIDGE_HOST_IP = 192.168.3.154\n",
                 "# set APPLEBRIDGE_HOST_IP=<addr> only on etherhelper\n",
                 "#export APPLEBRIDGE_HOST_IP=192.168.3.154\n"):
        assert "local_env_has_host_ip" not in keys(report(local_env=text)), text


def test_a_key_that_merely_contains_the_name_is_not_the_name():
    # APPLEBRIDGE_HOST_IP_OLD= is somebody's note-to-self, not configuration.
    assert "local_env_has_host_ip" not in keys(
        report(local_env="APPLEBRIDGE_HOST_IP_OLD=192.168.3.154\n"))


def test_an_exported_assignment_still_counts():
    assert "local_env_has_host_ip" in keys(
        report(ether="slirp", netmode="slirp",
               local_env="export APPLEBRIDGE_HOST_IP=192.168.3.154\n"))


def test_a_recorded_emulator_that_is_gone_is_named():
    # Exactly what happens after clearing a Gatekeeper quarantine and moving the
    # bundle: start_stack.sh hands `open` a path that is not there.
    rep = report(missing_paths=("BasiliskII.app",))
    assert "emulator_app_stale" in keys(rep)
    f = [x for x in rep["findings"] if x["key"] == "emulator_app_stale"][0]
    assert "install_bridge.py" in f["fix"]


def test_a_missing_deployed_copy_is_an_error_when_the_agent_is_installed():
    # launchd cannot read the repo under TCC-protected ~/Documents, so it runs a
    # synced copy. Agent installed with nothing to run is a dead stack.
    rep = report(missing_paths=("host_server.py",))
    assert "deploy_missing" in keys(rep)
    assert [x for x in rep["findings"]
            if x["key"] == "deploy_missing"][0]["level"] == "error"


def test_no_deployed_copy_is_not_an_error_without_the_agent():
    # --no-agent is a supported choice (R12): the repo is run directly, and
    # there is no deployed copy to miss.
    assert "deploy_missing" not in keys(
        report(agent_installed=False, missing_paths=("host_server.py",)))


def test_an_absent_local_env_is_information_not_a_fault():
    rep = report(local_env="")
    assert "no_local_env" in keys(rep)
    assert [x for x in rep["findings"]
            if x["key"] == "no_local_env"][0]["level"] == "info"


def test_the_report_prints_what_it_examined():
    # A silent check is one nobody trusts and everybody re-does by hand.
    text = bd.format_text(report())
    for label in ("local.env:", "emulator app:", "deployed copy:"):
        assert label in text, label


# --- is the guest dialling an address this host still answers on? -----------
# The daemon dials OUT, so a stale IP= presents as a daemon hanging on
# CONNECTING with no explanation — or, on a LAN where the stale address answers,
# as a bridge that reaches somebody ELSE'S machine and reports full health (R2).
# Until now that value lived only inside the guest, and reading it meant booting
# the guest — exactly what a broken bridge prevents. hfsutils reads a
# POWERED-OFF image directly, so the check costs nothing.

def _with_guest_ip(ip, addrs=("192.168.3.154", "192.168.3.240")):
    """A report whose guest_ip probe is stubbed, so the FINDING is under test
    rather than hfsutils."""
    real = bd.probe_guest_ip
    bd.probe_guest_ip = lambda *a, **k: {"ip": ip, "image": "/tmp/img.dmg",
                                         "checked": True, "why": ""}
    try:
        return report(en0=addrs)
    finally:
        bd.probe_guest_ip = real


def test_a_guest_dialling_an_address_we_do_not_have_is_an_error():
    rep = _with_guest_ip("10.9.9.9")
    assert "guest_ip_stale" in keys(rep)
    f = [x for x in rep["findings"] if x["key"] == "guest_ip_stale"][0]
    assert f["level"] == "error"
    assert "10.9.9.9" in f["message"]
    assert "--seed-guest-prefs" in f["fix"], "the fix must be runnable"


def test_a_guest_dialling_one_of_our_addresses_is_silent():
    assert "guest_ip_stale" not in keys(_with_guest_ip("192.168.3.240"))


def test_the_check_compares_against_the_addresses_we_actually_have():
    # The first version read net["addresses"], a key that does not exist — so
    # the finding could NEVER fire. A check that cannot fail is precisely what
    # this module exists to catch, and it was written into the check for
    # catching it. This test fails if that regresses.
    rep = _with_guest_ip("10.9.9.9")
    f = [x for x in rep["findings"] if x["key"] == "guest_ip_stale"][0]
    assert "192.168.3.240" in f["message"], \
        "the host's real addresses must appear; an empty set makes this inert"


def test_a_running_emulator_means_the_image_is_not_touched():
    # Mounting a live image risks the HFS volume, and the running daemon holds
    # its own copy of the prefs anyway (R14).
    got = bd.probe_guest_ip(lambda argv: "", ["/tmp/x.dmg"], emulator_running=True)
    assert got["checked"] is False
    assert "running" in got["why"]


def test_no_disk_image_is_reported_as_not_checked_not_as_healthy():
    got = bd.probe_guest_ip(lambda argv: "", [], emulator_running=False)
    assert got["checked"] is False and got["ip"] is None


def test_absent_hfsutils_is_named_instead_of_blamed_on_the_images():
    # Measured 2026-07-31: a host with all three images present and readable and
    # no hfsutils reported "no readable disk image in the emulator prefs" — a
    # plausible, wrong cause that sends the reader after a corrupt disk. Every
    # hmount returns nothing when the tool is absent, so the fall-through reason
    # can never distinguish the two on its own; the tool has to be declared.
    got = bd.probe_guest_ip(lambda argv: "", ["/tmp/x.dmg"],
                            emulator_running=False,
                            exists=lambda p: True, which=lambda name: None)
    assert got["checked"] is False and got["ip"] is None
    assert "hfsutils" in got["why"]
    assert "image" not in got["why"].split("hfsutils")[0]


def test_absent_hfsutils_does_not_swallow_the_no_image_case():
    # Ordering guard: if the hfsutils check ran first, a machine with no disk
    # image configured would be told to install a tool it has no use for.
    got = bd.probe_guest_ip(lambda argv: "", [], emulator_running=False,
                            exists=lambda p: True, which=lambda name: None)
    assert "hfsutils" not in got["why"]


def test_the_header_prints_what_the_guest_dials():
    text = bd.format_text(_with_guest_ip("192.168.3.240"))
    assert "guest dials:" in text



def test_a_probe_survives_MacRoman_bytes_in_its_own_output():
    """`hls` prints Mac filenames as the volume stores them — MacRoman, not UTF-8.

    Measured 2026-08-06 while diagnosing a live bridge: `_run` used
    `subprocess.run(..., text=True)`, which decodes with the STRICT default, so
    one umlaut in a folder name at the root of a guest image raised
    UnicodeDecodeError out of `communicate` and took the entire report down —
    while the error message on the control port was telling the operator to run
    exactly this tool.

    A probe whose docstring promises "never raise" must survive its own input,
    and the input of a Mac-facing probe is not UTF-8. Pinned with a real
    MacRoman byte (0xAA = the trademark sign) rather than a placeholder."""
    import tempfile
    # A real `hls -l` line as a German guest stores it: "Systemordner" plus a
    # MacRoman byte no UTF-8 decoder accepts.
    raw = b"d/d 0 0 Systemordner\xaa Wed Aug  6 19:00 2026\n"
    with tempfile.NamedTemporaryFile(suffix=".txt", delete=False) as fh:
        fh.write(raw)
        path = fh.name
    try:
        out = bd._run(["/bin/cat", path])
    finally:
        os.unlink(path)
    assert "Systemordner" in out, out
    assert out                      # degraded to text, not to an exception

if __name__ == "__main__":
    tests = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    failed = 0
    for t in tests:
        try:
            t()
            print(f"ok   {t.__name__}")
        except AssertionError as e:
            failed += 1
            print(f"FAIL {t.__name__}: {e}")
    print(f"\n{len(tests) - failed}/{len(tests)} passed")
    sys.exit(1 if failed else 0)
