#!/usr/bin/env python3
"""
Generate the AppleBridge Installer's Finder icon as Rez `data` statements.

Same approach as mac/controlpanel/gen_icon.py, and for the same reason: a code
generator so the icon is reproducible and reviewable rather than hand-packed
hex, and so a change is a diff instead of an opaque blob.

WHY the installer needs one at all: the kit volume shows four applications with
identical generic icons, and a newcomer has no way to tell which one to run.
That is the same discoverability problem as the silent helper picker — the
program is correct and the person in front of it is stuck. A distinct icon is
the cheapest possible fix.

Motif: a package with an arrow coming down into it — the one drawing everybody
reads as "install" — over the blue AppleBridge arch so it still belongs to the
suite.

Emits ICN# (32x32 1-bit + mask), icl4 (32x32 4-bit), ics#/ics4 (16x16), plus
FREF/BNDL and the 'ABis' signature resource, all at id 128 (the application
convention, where the control panel uses its cdev range).

Run on the host:  python3 gen_installer_icon.py  ->  installer_icon.r
"""

PAL = {'.': 0, 'W': 0, 'B': 6, 'K': 15, 'L': 12, 'M': 13, 'D': 14, 'T': 0}
INK = set('KBMD')        # black/blue/greys read as "ink" in the 1-bit icon
OPAQUE = set('WBKLMD')   # everything but 'T' is part of the shape

RES_ID = 128             # applications conventionally use 128


def blank(n):
    return [['T'] * n for _ in range(n)]


def draw(n):
    """n x n: a package (lower two thirds) with an arrow descending into it."""
    g = blank(n)
    s = n / 32.0

    def px(x, y, c):
        xi, yi = int(round(x * s)), int(round(y * s))
        if 0 <= xi < n and 0 <= yi < n:
            g[yi][xi] = c

    def box(x0, y0, x1, y1, edge, fill=None):
        for y in range(y0, y1 + 1):
            for x in range(x0, x1 + 1):
                on_edge = x in (x0, x1) or y in (y0, y1)
                if on_edge:
                    px(x, y, edge)
                elif fill:
                    px(x, y, fill)

    # --- the package -----------------------------------------------------
    box(4, 16, 27, 28, 'K', 'L')          # body
    box(4, 16, 27, 19, 'K', 'M')          # lid band
    for x in range(5, 27):                # lid shadow line
        px(x, 20, 'D')

    # --- the arrow, descending into the lid ------------------------------
    for y in range(3, 12):                # shaft
        px(15, y, 'B'); px(16, y, 'B')
    for i in range(6):                    # head
        for x in range(15 - i, 17 + i):
            px(x, 11 + i, 'B')

    # --- the AppleBridge arch, small, on the package face -----------------
    for x in range(8, 24):
        dy = ((x - 15.5) / 7.5) ** 2
        px(x, int(25 - 2.5 * (1 - dy)), 'B')
    px(8, 26, 'B'); px(23, 26, 'B')

    return g


def bits1(g, pred):
    out = bytearray()
    n = len(g)
    for row in g:
        acc, bit = 0, 0
        for x in range(n):
            acc = (acc << 1) | (1 if pred(row[x]) else 0)
            bit += 1
            if bit == 8:
                out.append(acc); acc, bit = 0, 0
        if bit:
            out.append(acc << (8 - bit))
    return bytes(out)


def nibbles4(g):
    out = bytearray()
    for row in g:
        for i in range(0, len(row), 2):
            out.append((PAL[row[i]] << 4) | PAL[row[i + 1]])
    return bytes(out)


def hexblock(b, per=16):
    lines = []
    for i in range(0, len(b), per):
        chunk = b[i:i + per]
        pairs = ' '.join(chunk.hex()[j:j + 4] for j in range(0, len(chunk.hex()), 4))
        lines.append('\t$"%s"' % pairs)
    return '\n'.join(lines)


def data_res(typ, rid, b):
    return "data '%s' (%d, purgeable) {\n%s\n};\n" % (typ, rid, hexblock(b))


if __name__ == "__main__":
    g32, g16 = draw(32), draw(16)
    icn = bits1(g32, lambda c: c in INK) + bits1(g32, lambda c: c in OPAQUE)
    ics = bits1(g16, lambda c: c in INK) + bits1(g16, lambda c: c in OPAQUE)

    # FREF: this signature's documents/app -> 'APPL', local id 0
    fref = bytes.fromhex('4150504c' + '0000' + '00')
    # BNDL: creator 'ABis', 2 arrays (FREF, ICN#), each mapping local 0 -> 128
    bndl = bytes.fromhex(
        '41426973' + '0000' + '0001' +
        '46524546' + '0000' + '0000' + '%04x' % RES_ID +
        '49434e23' + '0000' + '0000' + '%04x' % RES_ID)
    sig = bytes([len('AppleBridge Installer')]) + b'AppleBridge Installer'

    parts = [
        "/* AppleBridge Installer icon - GENERATED by gen_installer_icon.py;",
        "   do not hand-edit. Rez this ONTO the built app, and give the file the",
        "   bundle bit (SetFile -a B) or the Finder will not look for it. */", "",
        data_res('ICN#', RES_ID, icn), data_res('icl4', RES_ID, nibbles4(g32)),
        data_res('ics#', RES_ID, ics), data_res('ics4', RES_ID, nibbles4(g16)),
        data_res('FREF', RES_ID, fref), data_res('BNDL', RES_ID, bndl),
        data_res('ABis', 0, sig),
    ]
    open('installer_icon.r', 'w').write('\n'.join(parts))
    print("wrote installer_icon.r")

    legend = {'T': ' ', 'W': '.', 'L': ':', 'B': '#', 'K': '@', 'M': 'o', 'D': '-'}
    print('\n'.join(''.join(legend[c] for c in row) for row in g32))
